-- VHDL Entity Computer_Exercise_5_lib.C5_Dislay_Top_Level.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-709-SPC)
--          at - 16:27:16 21.01.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C5_Dislay_Top_Level IS
   PORT( 
      clk           : IN     std_logic;
      frame_written : IN     std_logic;
      pixd_in       : IN     std_logic_vector (23 DOWNTO 0);
      rst_n         : IN     std_logic;
      write         : IN     std_logic;
      xw            : IN     std_logic_vector (7 DOWNTO 0);
      yw            : IN     std_logic_vector (7 DOWNTO 0);
      channel       : OUT    std_logic_vector (7 DOWNTO 0);
      lat           : OUT    std_logic;
      s_clk         : OUT    std_logic;
      s_rst         : OUT    std_logic;
      s_sda         : OUT    std_logic;
      sb            : OUT    std_logic;
      w_rdy         : OUT    std_logic
   );

-- Declarations

END C5_Dislay_Top_Level ;

--
-- VHDL Architecture Computer_Exercise_5_lib.C5_Dislay_Top_Level.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-709-SPC)
--          at - 16:27:16 21.01.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_5_lib;

ARCHITECTURE struct OF C5_Dislay_Top_Level IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit_c      : std_logic;
   SIGNAL bit_g      : std_logic;
   SIGNAL bit_in     : std_logic;
   SIGNAL done       : std_logic;
   SIGNAL pixd       : std_logic_vector(23 DOWNTO 0);
   SIGNAL ready      : std_logic;
   SIGNAL rx_ready   : std_logic;
   SIGNAL rx_ready_c : std_logic;
   SIGNAL transmit   : std_logic;
   SIGNAL tx_c       : std_logic;
   SIGNAL tx_g       : std_logic;
   SIGNAL xr         : std_logic_vector(7 DOWNTO 0);
   SIGNAL yr         : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL sb_internal : std_logic;


   -- Component Declarations
   COMPONENT reg_bank
   PORT (
      clk      : IN     std_logic;
      pixd_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n    : IN     std_logic;
      w_done   : IN     std_logic;
      write    : IN     std_logic;
      xr       : IN     std_logic_vector (7 DOWNTO 0);
      xw       : IN     std_logic_vector (7 DOWNTO 0);
      yr       : IN     std_logic_vector (7 DOWNTO 0);
      yw       : IN     std_logic_vector (7 DOWNTO 0);
      pixd_out : OUT    std_logic_vector (23 DOWNTO 0);
      w_rdy    : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT serial_led_cannon
   PORT (
      clk     : IN     std_logic;
      pixdata : IN     std_logic_vector (23 DOWNTO 0);
      rst_n   : IN     std_logic;
      run     : IN     std_logic;
      bit_out : OUT    std_logic;
      chans   : OUT    std_logic_vector (7 DOWNTO 0);
      lat     : OUT    std_logic;
      tx      : OUT    std_logic;
      x       : OUT    std_logic_vector (7 DOWNTO 0);
      y       : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT v2_gamma
   PORT (
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      run     : IN     std_logic;
      bit_out : OUT    std_logic;
      sb      : OUT    std_logic;
      tx      : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT v2_rst
   PORT (
      clk   : IN     std_logic;
      rst_n : IN     std_logic;
      done  : OUT    std_logic;
      s_rst : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT v2_serial_tx
   PORT (
      bit_in     : IN     std_logic;
      clk        : IN     std_logic;
      rst_n      : IN     std_logic;
      run        : IN     std_logic;
      s_clk      : OUT    std_logic;
      s_sda      : OUT    std_logic;
      zc1f6aeab5 : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : reg_bank USE ENTITY Computer_Exercise_5_lib.reg_bank;
   FOR ALL : serial_led_cannon USE ENTITY Computer_Exercise_5_lib.serial_led_cannon;
   FOR ALL : v2_gamma USE ENTITY Computer_Exercise_5_lib.v2_gamma;
   FOR ALL : v2_rst USE ENTITY Computer_Exercise_5_lib.v2_rst;
   FOR ALL : v2_serial_tx USE ENTITY Computer_Exercise_5_lib.v2_serial_tx;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   rx_ready <= done AND ready;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   rx_ready_c <= ready AND sb_internal;

   -- ModuleWare code(v1.12) for instance 'sel_tx_bit' of 'mux'
   sel_tx_bitcombo_proc: PROCESS(bit_g, bit_c, sb_internal)
   BEGIN
      CASE sb_internal IS
      WHEN '0' => bit_in <= bit_g;
      WHEN '1' => bit_in <= bit_c;
      WHEN OTHERS => bit_in <= 'X';
      END CASE;
   END PROCESS sel_tx_bitcombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'or'
   transmit <= tx_g OR tx_c;

   -- Instance port mappings.
   U_3 : reg_bank
      PORT MAP (
         clk      => clk,
         pixd_in  => pixd_in,
         rst_n    => rst_n,
         w_done   => frame_written,
         write    => write,
         xr       => xr,
         xw       => yw,
         yr       => yr,
         yw       => xw,
         pixd_out => pixd,
         w_rdy    => w_rdy
      );
   U_2 : serial_led_cannon
      PORT MAP (
         clk     => clk,
         pixdata => pixd,
         rst_n   => rst_n,
         run     => rx_ready_c,
         bit_out => bit_c,
         chans   => channel,
         lat     => lat,
         tx      => tx_c,
         x       => xr,
         y       => yr
      );
   U_0 : v2_gamma
      PORT MAP (
         clk     => clk,
         rst_n   => rst_n,
         run     => rx_ready,
         bit_out => bit_g,
         sb      => sb_internal,
         tx      => tx_g
      );
   U_8 : v2_rst
      PORT MAP (
         clk   => clk,
         rst_n => rst_n,
         done  => done,
         s_rst => s_rst
      );
   U_1 : v2_serial_tx
      PORT MAP (
         bit_in     => bit_in,
         clk        => clk,
         rst_n      => rst_n,
         run        => transmit,
         zc1f6aeab5 => ready,
         s_clk      => s_clk,
         s_sda      => s_sda
      );

   -- Implicit buffered output assignments
   sb <= sb_internal;

END struct;
