-- VHDL Entity Computer_Exercise_3_lib.C3_T3_Button_Debounce.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-707-SPC)
--          at - 15:09:14  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C3_T3_Button_Debounce IS
   PORT( 
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      btn_out : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END C3_T3_Button_Debounce ;

--
-- VHDL Architecture Computer_Exercise_3_lib.C3_T3_Button_Debounce.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-707-SPC)
--          at - 15:09:11  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_3_lib;

ARCHITECTURE struct OF C3_T3_Button_Debounce IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL btn_filtered  : std_logic;
   SIGNAL btn_filtered1 : std_logic;
   SIGNAL btn_filtered2 : std_logic;
   SIGNAL btn_in        : std_logic;
   SIGNAL btn_in1       : std_logic;
   SIGNAL din2          : std_logic;
   SIGNAL dout0         : std_logic;
   SIGNAL dout3         : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'split'
   SIGNAL mw_U_5temp_din : std_logic_vector(3 DOWNTO 0);

   -- Component Declarations
   COMPONENT Button_Filter
   PORT (
      btn_in       : IN     std_logic ;
      clk          : IN     std_logic ;
      rst          : IN     std_logic ;
      btn_filtered : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Button_Filter USE ENTITY Computer_Exercise_3_lib.Button_Filter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'merge'
   btn_out <= btn_filtered2 & din2 & btn_filtered1 & btn_filtered;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'split'
   mw_U_5temp_din <= btn;
   u_5combo_proc: PROCESS (mw_U_5temp_din)
   VARIABLE temp_din: std_logic_vector(3 DOWNTO 0);
   BEGIN
      temp_din := mw_U_5temp_din(3 DOWNTO 0);
      dout0 <= temp_din(0);
      btn_in <= temp_din(1);
      btn_in1 <= temp_din(2);
      dout3 <= temp_din(3);
   END PROCESS u_5combo_proc;

   -- Instance port mappings.
   U_0 : Button_Filter
      PORT MAP (
         btn_in       => dout0,
         clk          => clk,
         rst          => rst_n,
         btn_filtered => btn_filtered
      );
   U_1 : Button_Filter
      PORT MAP (
         btn_in       => btn_in,
         clk          => clk,
         rst          => rst_n,
         btn_filtered => btn_filtered1
      );
   U_2 : Button_Filter
      PORT MAP (
         btn_in       => btn_in1,
         clk          => clk,
         rst          => rst_n,
         btn_filtered => din2
      );
   U_4 : Button_Filter
      PORT MAP (
         btn_in       => dout3,
         clk          => clk,
         rst          => rst_n,
         btn_filtered => btn_filtered2
      );

END struct;
