-- VHDL Entity Computer_Exercise_3_lib.C3_T4_Bullet.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-718-SPC)
--          at - 17:06:30 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C3_T4_Bullet IS
   PORT( 
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      gun_x_coord    : IN     std_logic_vector (7 DOWNTO 0);
      rst_n          : IN     std_logic;
      bullet_color   : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END C3_T4_Bullet ;

--
-- VHDL Architecture Computer_Exercise_3_lib.C3_T4_Bullet.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-718-SPC)
--          at - 17:06:30 21.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exerccise_2_lib;
LIBRARY Computer_Exercise_4_hdl_lib;

ARCHITECTURE struct OF C3_T4_Bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL coord_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL d       : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1   : std_logic;
   SIGNAL dout3   : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4   : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5   : std_logic_vector(7 DOWNTO 0);
   SIGNAL equal   : std_logic;
   SIGNAL y       : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL bullet_x_coord_internal : std_logic_vector (7 DOWNTO 0);
   SIGNAL bullet_y_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_11' of 'adff'
   SIGNAL mw_U_11reg_cval : std_logic_vector(23 DOWNTO 0);

   -- Component Declarations
   COMPONENT C2_T4_Rightshifter
   PORT (
      x : IN     std_logic_vector (7 DOWNTO 0);
      y : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT Coordinate_Compare
   PORT (
      coord_1 : IN     std_logic_vector (7 DOWNTO 0);
      coord_2 : IN     std_logic_vector (7 DOWNTO 0);
      equal   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C2_T4_Rightshifter USE ENTITY Computer_Exerccise_2_lib.C2_T4_Rightshifter;
   FOR ALL : Coordinate_Compare USE ENTITY Computer_Exercise_4_hdl_lib.Coordinate_Compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   bullet_x_coord_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_0reg_cval <= "00000000";
         ELSE
            mw_U_0reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   bullet_y_coord_internal <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_5reg_cval <= "00000000";
         ELSE
            mw_U_5reg_cval <= dout3;
         END IF;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'adff'
   bullet_color <= mw_U_11reg_cval;
   u_11seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_11reg_cval <= "000000000000000000010001";
         ELSE
            mw_U_11reg_cval <= d;
         END IF;
      END IF;
   END PROCESS u_11seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout1 <= equal AND btn(0);

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout5 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   d <= "111111111000000010000000";

   -- ModuleWare code(v1.12) for instance 'U_13' of 'constval'
   coord_2 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(bullet_x_coord_internal, gun_x_coord, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => dout <= bullet_x_coord_internal;
      WHEN '1' => dout <= gun_x_coord;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(bullet_y_coord_internal, y, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout4 <= bullet_y_coord_internal;
      WHEN '1' => dout4 <= y;
      WHEN OTHERS => dout4 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(dout4, dout5, dout1)
   BEGIN
      CASE dout1 IS
      WHEN '0' => dout3 <= dout4;
      WHEN '1' => dout3 <= dout5;
      WHEN OTHERS => dout3 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_3 : C2_T4_Rightshifter
      PORT MAP (
         x => bullet_y_coord_internal,
         y => y
      );
   U_2 : Coordinate_Compare
      PORT MAP (
         coord_1 => bullet_y_coord_internal,
         coord_2 => coord_2,
         equal   => equal
      );

   -- Implicit buffered output assignments
   bullet_x_coord <= bullet_x_coord_internal;
   bullet_y_coord <= bullet_y_coord_internal;

END struct;
