-- VHDL Entity Computer_Exercise_3_lib.Gun_pixel.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-705-SPC)
--          at - 12:26:18 25.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Gun_pixel IS
   PORT( 
      clk        : IN     std_logic;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic;
      x_internal : IN     std_logic_vector (7 DOWNTO 0);
      x_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END Gun_pixel ;

--
-- VHDL Architecture Computer_Exercise_3_lib.Gun_pixel.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-707-SPC)
--          at - 16:01:24  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exerccise_2_lib;

ARCHITECTURE struct OF Gun_pixel IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d        : std_logic_vector(7 DOWNTO 0);
   SIGNAL data_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2    : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT C2_T3_Leftshifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT C2_T4_Rightshifter
   PORT (
      x : IN     std_logic_vector (7 DOWNTO 0);
      y : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C2_T3_Leftshifter USE ENTITY Computer_Exerccise_2_lib.C2_T3_Leftshifter;
   FOR ALL : C2_T4_Rightshifter USE ENTITY Computer_Exerccise_2_lib.C2_T4_Rightshifter;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   x_coord <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00001010";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= d;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   y_coord <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_5reg_cval <= "01000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= dout;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout1 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(data_out, x_internal, din2, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => d <= data_out;
      WHEN "01" => d <= x_internal;
      WHEN "10" => d <= din2;
      WHEN "11" => d <= x_internal;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(dout2, dout1, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => dout <= dout2;
      WHEN "01" => dout <= dout1;
      WHEN "10" => dout <= dout2;
      WHEN "11" => dout <= dout2;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_2 : C2_T3_Leftshifter
      PORT MAP (
         data_in  => x_internal,
         data_out => data_out
      );
   U_3 : C2_T4_Rightshifter
      PORT MAP (
         x => x_internal,
         y => din2
      );

END struct;
