-- VHDL Entity tb_lib.tb_debounce.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-707-SPC)
--          at - 13:47:36 07/27/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_debounce IS
-- Declarations

END tb_debounce ;

--
-- VHDL Architecture tb_lib.tb_debounce.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-707-SPC)
--          at - 15:30:31  1.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_3_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_debounce IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL btn     : std_logic_vector(3 DOWNTO 0);
   SIGNAL btn_out : std_logic_vector(3 DOWNTO 0);
   SIGNAL clk     : std_logic;
   SIGNAL rst_n   : std_logic;


   -- Component Declarations
   COMPONENT C3_T3_Button_Debounce
   PORT (
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic ;
      rst_n   : IN     std_logic ;
      btn_out : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT debounce_tester
   PORT (
      button_from_duv : IN     std_logic;
      button_to_DUV   : OUT    std_logic;
      clk             : OUT    std_logic;
      rst_n           : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C3_T3_Button_Debounce USE ENTITY Computer_Exercise_3_lib.C3_T3_Button_Debounce;
   FOR ALL : debounce_tester USE ENTITY tb_lib.debounce_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : C3_T3_Button_Debounce
      PORT MAP (
         btn     => btn,
         clk     => clk,
         rst_n   => rst_n,
         btn_out => btn_out
      );
   U_0 : debounce_tester
      PORT MAP (
         button_from_duv => btn_out(0),
         button_to_DUV   => btn(0),
         clk             => clk,
         rst_n           => rst_n
      );

END struct;
