-- VHDL Entity tb_lib.tb_decrementer.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-708-SPC)
--          at - 13:34:35 06/11/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_decrementer IS
-- Declarations

END tb_decrementer ;

--
-- VHDL Architecture tb_lib.tb_decrementer.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-708-SPC)
--          at - 11:15:09 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.numeric_std.all;

LIBRARY Computer_Exerccise_2_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL correct : std_logic;
   SIGNAL res     : std_logic_vector(2 DOWNTO 0);
   SIGNAL to_duv  : std_logic_vector(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT C2_T2_Decrementer
   PORT (
      Input  : IN     std_logic_vector (2 DOWNTO 0);
      Output : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT decrementer_tester_block
   PORT (
      res     : IN     std_logic_vector (2 DOWNTO 0);
      correct : OUT    std_logic ;
      to_duv  : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C2_T2_Decrementer USE ENTITY Computer_Exerccise_2_lib.C2_T2_Decrementer;
   FOR ALL : decrementer_tester_block USE ENTITY tb_lib.decrementer_tester_block;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : C2_T2_Decrementer
      PORT MAP (
         Input  => to_duv,
         Output => res
      );
   U_0 : decrementer_tester_block
      PORT MAP (
         res     => res,
         correct => correct,
         to_duv  => to_duv
      );

END struct;
