-- VHDL Entity tb_lib.tb_gamma.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-712-SPC)
--          at - 16:08:52 06/04/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_gamma IS
-- Declarations

END tb_gamma ;

--
-- VHDL Architecture tb_lib.tb_gamma.struct
--
-- Created:
--          by - qkrasi.UNKNOWN (HTC219-712-SPC)
--          at - 11:20:22  5.12.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_5_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_gamma IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit         : std_logic;
   SIGNAL clk         : std_logic;
   SIGNAL gamma_value : std_logic_vector(5 DOWNTO 0);
   SIGNAL rst_n       : std_logic;
   SIGNAL rx_rdy      : std_logic;
   SIGNAL sb          : std_logic;
   SIGNAL tx          : std_logic;


   -- Component Declarations
   COMPONENT C5_T1_Shield_Gama
   PORT (
      clk      : IN     std_logic ;
      rst      : IN     std_logic ;
      rx_rdy   : IN     std_logic ;
      bit_out  : OUT    std_logic ;
      lat      : OUT    std_logic ;
      sb       : OUT    std_logic ;
      transmit : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT gamma_set_tester
   PORT (
      bit         : IN     std_logic ;
      sb          : IN     std_logic ;
      tx          : IN     std_logic ;
      clk         : OUT    std_logic ;
      gamma_value : OUT    std_logic_vector (5 DOWNTO 0);
      rst_n       : OUT    std_logic ;
      rx_rdy      : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C5_T1_Shield_Gama USE ENTITY Computer_Exercise_5_lib.C5_T1_Shield_Gama;
   FOR ALL : gamma_set_tester USE ENTITY tb_lib.gamma_set_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : C5_T1_Shield_Gama
      PORT MAP (
         clk      => clk,
         rst      => rst_n,
         rx_rdy   => rx_rdy,
         bit_out  => bit,
         lat      => OPEN,
         sb       => sb,
         transmit => tx
      );
   U_0 : gamma_set_tester
      PORT MAP (
         bit         => bit,
         sb          => sb,
         tx          => tx,
         clk         => clk,
         gamma_value => gamma_value,
         rst_n       => rst_n,
         rx_rdy      => rx_rdy
      );

END struct;
