-- VHDL Entity tb_lib.tb_shift_up.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-713-SPC)
--          at - 13:29:49 07/30/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_shift_up IS
-- Declarations

END tb_shift_up ;

--
-- VHDL Architecture tb_lib.tb_shift_up.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-713-SPC)
--          at - 13:50:02 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exerccise_2_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_shift_up IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL correct         : std_logic;
   SIGNAL from_up_shifter : std_logic_vector(7 DOWNTO 0);
   SIGNAL to_up_shifter   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT C2_T3_Leftshifter
   PORT (
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT shift_up_tester
   PORT (
      from_up_shifter : IN     std_logic_vector (7 DOWNTO 0);
      correct         : OUT    std_logic;
      to_up_shifter   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C2_T3_Leftshifter USE ENTITY Computer_Exerccise_2_lib.C2_T3_Leftshifter;
   FOR ALL : shift_up_tester USE ENTITY tb_lib.shift_up_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : C2_T3_Leftshifter
      PORT MAP (
         data_in  => to_up_shifter,
         data_out => from_up_shifter
      );
   U_0 : shift_up_tester
      PORT MAP (
         from_up_shifter => from_up_shifter,
         correct         => correct,
         to_up_shifter   => to_up_shifter
      );

END struct;
