-- VHDL Entity tb_lib.tb_shield_rst.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-711-SPC)
--          at - 15:12:39 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_shield_rst IS
-- Declarations

END tb_shield_rst ;

--
-- VHDL Architecture tb_lib.tb_shield_rst.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-711-SPC)
--          at - 12:38:24  8.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_4_hdl_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_shield_rst IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL done  : std_logic;
   SIGNAL rst_n : std_logic;
   SIGNAL s_rst : std_logic;


   -- Component Declarations
   COMPONENT C4_T4_Shield_Reset
   PORT (
      clk   : IN     std_logic ;
      rst   : IN     std_logic ;
      done  : OUT    std_logic ;
      s_rst : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT shield_rst_block
   PORT (
      done  : IN     std_logic;
      s_rst : IN     std_logic;
      clk   : OUT    std_logic;
      rst_n : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : C4_T4_Shield_Reset USE ENTITY Computer_Exercise_4_hdl_lib.C4_T4_Shield_Reset;
   FOR ALL : shield_rst_block USE ENTITY tb_lib.shield_rst_block;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : C4_T4_Shield_Reset
      PORT MAP (
         clk   => clk,
         rst   => rst_n,
         done  => done,
         s_rst => s_rst
      );
   U_0 : shield_rst_block
      PORT MAP (
         clk   => clk,
         rst_n => rst_n,
         s_rst => s_rst,
         done  => done
      );

END struct;
