-- VHDL Entity Computer_Exercise_4_hdl_lib.C4_T1_Hit_Detector.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-705-SPC)
--          at - 12:09:28  4.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C4_T1_Hit_Detector IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      hit      : OUT    std_logic
   );

-- Declarations

END C4_T1_Hit_Detector ;

--
-- VHDL Architecture Computer_Exercise_4_hdl_lib.C4_T1_Hit_Detector.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-705-SPC)
--          at - 12:09:25  4.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Computer_Exercise_4_hdl_lib;

ARCHITECTURE struct OF C4_T1_Hit_Detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL d    : std_logic;
   SIGNAL din0 : std_logic;
   SIGNAL din1 : std_logic;
   SIGNAL din2 : std_logic;
   SIGNAL q    : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- Component Declarations
   COMPONENT Coordinate_Compare
   PORT (
      coord_1 : IN     std_logic_vector (7 DOWNTO 0);
      coord_2 : IN     std_logic_vector (7 DOWNTO 0);
      equal   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Coordinate_Compare USE ENTITY Computer_Exercise_4_hdl_lib.Coordinate_Compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   q <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_4reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_4reg_cval <= din2;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   hit <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_5reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= d;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   din2 <= din0 AND din1;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   d <= NOT(q) AND din2;

   -- Instance port mappings.
   U_0 : Coordinate_Compare
      PORT MAP (
         coord_1 => alien_x,
         coord_2 => bullet_x,
         equal   => din0
      );
   U_1 : Coordinate_Compare
      PORT MAP (
         coord_1 => alien_y,
         coord_2 => bullet_y,
         equal   => din1
      );

END struct;
