-- VHDL Entity Computer_Exercise_4_hdl_lib.C4_T5_Serial_Data_Transmit.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-717-SPC)
--          at - 11:22:54  7.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C4_T5_Serial_Data_Transmit IS
   PORT( 
      bit_in   : IN     std_logic;
      clk      : IN     std_logic;
      rst      : IN     std_logic;
      transmit : IN     std_logic;
      ready    : OUT    std_logic;
      s_clk    : OUT    std_logic;
      s_sda    : OUT    std_logic
   );

-- Declarations

END C4_T5_Serial_Data_Transmit ;

--
-- VHDL Architecture Computer_Exercise_4_hdl_lib.C4_T5_Serial_Data_Transmit.fsm
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-711-SPC)
--          at - 11:38:21  8.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF C4_T5_Serial_Data_Transmit IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(2 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(2 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s3 : std_logic;
   SIGNAL csm_to_s4 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s3 <= '0';
      csm_to_s4 <= '0';
      CASE current_state IS
         WHEN s0 => 
            IF (transmit = '1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            next_state <= s2;
         WHEN s2 => 
            next_state <= s3;
            csm_to_s3 <= '1';
         WHEN s3 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s4;
               csm_to_s4 <= '1';
            ELSE
               next_state <= s3;
            END IF;
         WHEN s4 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s4;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      bit_in,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      ready <= '1';
      s_clk <= '0';
      s_sda <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN s2 => 
            ready <= '0' ;
            s_sda <= bit_in ;
         WHEN s3 => 
            s_clk <= '0' ;
            s_sda <= bit_in;
            ready <= '0' ;
         WHEN s4 => 
            s_clk <= '1' ;
            s_sda <= bit_in;
            ready <= '0' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s3,
      csm_to_s4
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s3 = '1') THEN
         csm_next_timer <= "011"; -- no cycles(4)-1=3
      ELSIF (csm_to_s4 = '1') THEN
         csm_next_timer <= "011"; -- no cycles(4)-1=3
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
