-- VHDL Entity Computer_Exercise_4_hdl_lib.Coordinate_Compare.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-705-SPC)
--          at - 11:29:49  4.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Coordinate_Compare IS
   PORT( 
      coord_1 : IN     std_logic_vector (7 DOWNTO 0);
      coord_2 : IN     std_logic_vector (7 DOWNTO 0);
      equal   : OUT    std_logic
   );

-- Declarations

END Coordinate_Compare ;

--
-- VHDL Architecture Computer_Exercise_4_hdl_lib.Coordinate_Compare.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-705-SPC)
--          at - 11:38:44  4.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Coordinate_Compare IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1  : std_logic;
   SIGNAL din3  : std_logic;
   SIGNAL din5  : std_logic;
   SIGNAL din7  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   equal <= dout AND din1 AND dout1 AND din3 AND dout3 AND din5 AND dout2
            AND din7;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'xnor'
   dout <= NOT(coord_1(0) XOR coord_2(0));

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xnor'
   din1 <= NOT(coord_1(1) XOR coord_2(1));

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xnor'
   dout1 <= NOT(coord_1(2) XOR coord_2(2));

   -- ModuleWare code(v1.12) for instance 'U_3' of 'xnor'
   din3 <= NOT(coord_1(3) XOR coord_2(3));

   -- ModuleWare code(v1.12) for instance 'U_4' of 'xnor'
   dout3 <= NOT(coord_1(4) XOR coord_2(4));

   -- ModuleWare code(v1.12) for instance 'U_5' of 'xnor'
   din5 <= NOT(coord_1(5) XOR coord_2(5));

   -- ModuleWare code(v1.12) for instance 'U_6' of 'xnor'
   dout2 <= NOT(coord_1(6) XOR coord_2(6));

   -- ModuleWare code(v1.12) for instance 'U_7' of 'xnor'
   din7 <= NOT(coord_1(7) XOR coord_2(7));

   -- Instance port mappings.

END struct;
