-- VHDL Entity Computer_Exerccise_2_lib.C2_T4_Rightshifter.symbol
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-713-SPC)
--          at - 13:21:14 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY C2_T4_Rightshifter IS
   PORT( 
      x : IN     std_logic_vector (7 DOWNTO 0);
      y : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END C2_T4_Rightshifter ;

--
-- VHDL Architecture Computer_Exerccise_2_lib.C2_T4_Rightshifter.struct
--
-- Created:
--          by - mfhubu.UNKNOWN (HTC219-713-SPC)
--          at - 13:32:04 10.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF C2_T4_Rightshifter IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   y(6) <= x(7) AND x(7);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   y(5) <= x(6) AND x(6);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   y(4) <= x(5) AND x(5);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   y(3) <= x(4) AND x(4);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   y(2) <= x(3) AND x(3);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   y(1) <= x(2) AND x(2);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   y(0) <= x(1) AND x(1);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   y(7) <= '0';

   -- Instance port mappings.

END struct;
